services:
  pg:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_volume:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/postgresql.conf:/etc/postgresql.conf
      - ./:/var/tmp/src
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 25s
      timeout: 8s
      retries: 3
      start_period: 10s
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 7200:7200
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200/docs"]
      interval: 25s
      timeout: 8s
      retries: 3
      start_period: 10s
    restart: always
    depends_on:
      - pg
volumes:
  pg_volume:
